export const HTTP_CODES = {
  SUCCESSFUL: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
  },
  REDIRECTED: {
    MOVED_PERMANENTLY: 301,
    TEMPORARILY_REDIRECTED: 307,
  },
  CLIENT_ERROR: {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    REQUEST_TIMEOUT: 408,
    TEAPOT: 418,
    TOO_MANY_REQUESTS: 429,
  },
  SERVER_ERROR: {
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
  },
} as const;
